In [1]:
import torch
import torch.nn.functional as F
import numpy as np
x = torch.tensor([[[1.787,2.3452,3.9872,4.431545],
                  [3.2323, 3.3232, 4.3232, 4.43344]],
                  [[1.787,2.3452,3.9872,4.431545],
                  [3.2323, 3.3232, 4.3232, 4.43344]]])
x.float().reshape(x.shape[:-1] + (-1, 2)).unbind(-1)


(tensor([[[1.7870, 3.9872],
          [3.2323, 4.3232]],
 
         [[1.7870, 3.9872],
          [3.2323, 4.3232]]]),
 tensor([[[2.3452, 4.4315],
          [3.3232, 4.4334]],
 
         [[2.3452, 4.4315],
          [3.3232, 4.4334]]]))

In [7]:
i = 0
d = 512
# theta = 10000**(-2*i/d)
theta = [10000**(-2*i/d) for i in range(d)]


theta = np.sin(theta)
theta = torch.tensor(theta)


In [20]:
a = torch.tensor([1,2,3,4,5,6])
a = a.view(-1,2).flip(1).reshape(-1)
a

tensor([2, 1, 4, 3, 6, 5])

In [29]:
a = torch.tensor([1,3,5,7,9]).unsqueeze(-1)
b = torch.tensor([2,4,6,8,10]).unsqueeze(-1)

torch.cat((a,b), dim=-1).reshape(-1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
torch.cat((-b,a), dim=-1).reshape(-1)

tensor([ -2,   1,  -4,   3,  -6,   5,  -8,   7, -10,   9])

In [2]:
c = torch.tensor([[1,2,3,4],
                  [5,6,7,8]])
c

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [3]:
c.view(1,2,1,4)

tensor([[[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]]])

In [4]:
c.view(1,2,1,4).expand(2,2,2,4)

tensor([[[[1, 2, 3, 4],
          [1, 2, 3, 4]],

         [[5, 6, 7, 8],
          [5, 6, 7, 8]]],


        [[[1, 2, 3, 4],
          [1, 2, 3, 4]],

         [[5, 6, 7, 8],
          [5, 6, 7, 8]]]])

In [ ]:
torch.arange(0, 8, 2)

In [9]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 形状: (2, 2, 2)
tensor2 = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # 形状: (2, 2, 2)

# 在最后一维上堆叠
stacked = torch.stack((tensor1, tensor2), dim=-1).view(2,2,-1)  # 形状: (2, 2, 2, 2)
stacked

tensor([[[ 1,  9,  2, 10],
         [ 3, 11,  4, 12]],

        [[ 5, 13,  6, 14],
         [ 7, 15,  8, 16]]])

In [6]:
# 示例输入
tensor1 = torch.tensor([1, 3, 5])  # 形状: (3,)
tensor2 = torch.tensor([2, 4, 6])  # 形状: (3,)

# 堆叠并调整形状
result = torch.stack((tensor1, tensor2), dim=1).view(-1)
result

tensor([1, 2, 3, 4, 5, 6])

In [10]:
torch.arange(0, 4, 2)

tensor([0, 2])

In [12]:
torch.arange(0, 4//2)

tensor([0, 1])

In [13]:
a = torch.rand(3,2)
a = a.view(1,3,1,2)

query_real = torch.rand(2,3,2,2)

a*query_real

tensor([[[[4.0837e-01, 1.5514e-01],
          [5.2118e-01, 7.5280e-03]],

         [[2.3242e-04, 4.0424e-01],
          [3.2242e-01, 3.8954e-02]],

         [[2.3186e-01, 5.9872e-04],
          [3.4052e-01, 5.7783e-03]]],


        [[[6.2617e-01, 3.4871e-01],
          [1.9378e-01, 1.7009e-01]],

         [[2.8358e-01, 4.5051e-01],
          [3.8968e-01, 1.6449e-01]],

         [[3.2136e-01, 3.5772e-03],
          [2.4442e-01, 1.9247e-03]]]])

In [13]:
import torch

a = torch.tensor([445])
a = a.unsqueeze(0)

In [15]:
len(a.shape)

2